In [2]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_selector

## Modelo multivariable

In [25]:
df=pd.read_csv("metadata.csv")
df

,patientid,offset,sex,age,finding,survival,intubated,intubation_present,went_icu,in_icu,...,date,location,folder,filename,doi,url,license,clinical_notes,other_notes,Unnamed: 28
0,2,0.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 22, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-a-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
1,2,3.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 25, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-b-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
2,2,5.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 27, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-c-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
3,2,6.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 28, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-d-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
4,4,0.0,F,52.0,COVID-19,NaN,NaN,NaN,NaN,NaN,...,"January 25, 2020","Changhua Christian Hospital, Changhua City, Ta...",images,nejmc2001573_f1a.jpeg,10.1056/NEJMc2001573,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,diffuse infiltrates in the bilateral lower lungs,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,205,11.0,M,55.0,COVID-19,Y,NaN,Y,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,"ITU admission, Endotracheal tube, nasogastric ...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
368,205,13.0,M,55.0,COVID-19,Y,NaN,Y,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,Lines and tubes suitably sited. Minor regress...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
369,205,20.0,M,55.0,COVID-19,Y,NaN,Y,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,increasing oxygen requirements. Extubated. Po...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
370,205,24.0,M,55.0,COVID-19,Y,NaN,N,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,Extubated since the prior radiograph. Partial...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
371,205,28.0,M,55.0,COVID-19,Y,NaN,N,Y,N,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,Remarkable improvement in appearances since th...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN

In [26]:
enfermedades = df["finding"].unique().tolist()
enfermedades

['COVID-19',
 'ARDS',
 'SARS',
 'Pneumocystis',
 'Streptococcus',
 'No Finding',
 'Chlamydophila',
 'E.Coli',
 'COVID-19, ARDS',
 'Klebsiella',
 'Legionella']

In [27]:
catm_transformer = ColumnTransformer(
    [('onehot',OneHotEncoder(drop=['No Finding'],handle_unknown='ignore',sparse_output=False), ["finding"])],
    remainder='passthrough',
    verbose_feature_names_out=False).set_output(transform="pandas")
df=catm_transformer.fit_transform(df)

In [28]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,362,363,364,365,366,367,368,369,370,371
finding_ARDS,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_COVID-19,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
"finding_COVID-19, ARDS",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_Chlamydophila,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_E.Coli,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_Klebsiella,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_Legionella,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_Pneumocystis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_SARS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
finding_Streptococcus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
patientid,2,2,2,2,4,4,5,6,6,3,...,202,203,204,205,205,205,205,205,205,205
offset,0.0,3.0,5.0,6.0,0.0,5.0,NaN,0.0,4.0,4.0,...,3.0,0.0,5.0,1.0,6.0,11.0,13.0,20.0,24.0,28.0
sex,M,M,M,M,F,F,NaN,NaN,NaN,M,...,M,F,M,M,M,M,M,M,M,M
age,65.0,65.0,65.0,65.0,52.0,52.0,NaN,NaN,NaN,74.0,...,83.0,45.0,45.0,55.0,55.0,55.0,55.0,55.0,55.0,55.0
survival,Y,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,N,...,NaN,NaN,NaN,Y,Y,Y,Y,Y,Y,Y
intubated,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
intubation_present,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,Y,NaN,...,N,N,N,N,N,Y,Y,Y,N,N
went_icu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,Y,NaN,...,NaN,NaN,NaN,Y,Y,Y,Y,Y,Y,Y
in_icu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,N,N,Y,Y,Y,Y,N
needed_supplemental_O2,Y,Y,Y,Y,N,N,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
extubated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Y,Y,Y,Y,Y,Y,Y
temperature,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pO2_saturation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
leukocyte_count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neutrophil_count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lymphocyte_count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
view,PA,PA,PA,PA,PA,PA,PA,PA,PA,AP,...,AP Supine,AP,PA,AP,AP,AP Supine,AP Supine,AP Supine,AP Supine,AP
modality,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,...,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray,X-ray
date,"January 22, 2020","January 25, 2020","January 27, 2020","January 28, 2020","January 25, 2020","January 30, 2020",2017,"January 6, 2020","January 10, 2020",2004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,"Cho Ray Hospital, Ho Chi Minh City, Vietnam","Cho Ray Hospital, Ho Chi Minh City, Vietnam","Cho Ray Hospital, Ho Chi Minh City, Vietnam","Cho Ray Hospital, Ho Chi Minh City, Vietnam","Changhua Christian Hospital, Changhua City, Ta...","Changhua Christian Hospital, Changhua City, Ta...",NaN,"Wuhan Jinyintan Hospital, Wuhan, Hubei Provinc...","Wuhan Jinyintan Hospital, Wuhan, Hubei Provinc...","Mount Sinai Hospital, Toronto, Ontario, Canada",...,Italy,Pakistan,Turkey,"North Derbyshire, UK","North Derbyshire, UK","North Derbyshire, UK","North Derbyshire, UK","North Derbyshire, UK","North Derbyshire, UK","North Derbyshire, UK"
folder,images,images,images,images,images,images,images,images,images,images,...,images,images,images,images,images,images,images,images,images,images
filename,auntminnie-a-2020_01_28_23_51_6665_2020_01_28_...,auntminnie-b-2020_01_28_23_51_6665_2020_01_28_...,auntminnie-c-2020_01_28_23_51_6665_2020_01_28_...,auntminnie-d-2020_01_28_23_51_6665_2020_01_28_...,nejmc2001573_f1a.jpeg,nejmc2001573_f1b.jpeg,ARDSSevere.png,lancet-case2a.jpg,lancet-case2b.jpg,SARS-10.1148rg.242035193-g04mr34g0-Fig8a-day0....,...,case_76_1-3.png,covid-19-pneumonia-101.png,covid-19-pneumonia-93.png,covid-19-pneumonia-progression-and-regression-...,covid-19-pneumonia-progression-and-regression-...,covid-19-pneumonia-progression-and-regression-...,covid-19-pneumonia-progression-and-regression-...,covid-19-pneumonia-progression-and-regression-...,covid-19-pneumonia-progression-and-regression-...,covid-19-pneumonia-progression-and-regression-...
doi,10.1056/nejmc2001272,10.1056/nejmc2001272,10.1056/nejmc2001272,10.1056/nejmc2001272,10.1056/NEJMc2001573,10.1056/NEJMc2001573,NaN,10.1016/S0140-6736(20)30211-7,10.1016/S0140-6736(20)30211-7,10.1148/rg.242035193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
url,https://www.nejm.org/doi/full/10.1056/NEJMc200...,https://www.nejm.org/doi/full/10.1056/NEJMc200...,https://www.nejm.org/doi/full/10.1056/NEJMc200...,https://www.nejm.org/doi/full/10.1056/NEJMc200...,https://www.nejm.org/doi/full/10.1056/NEJMc200...,https://www.nejm.org/doi/full/10.1056/NEJMc200...,https://en.wikipedia.org/wiki/File:ARDSSevere.png,https://www.thelancet.com/journals/lancet/arti...,https://www.thelancet.com/journals/lancet/arti...,https://pubs.rsna.org/doi/10.1148/rg.242035193,...,https://www.sirm.org/2020/05/12/covid-19-caso-76/,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...,https://radiopaedia.org/cases/covid-19-pneumon...
license,NaN,NaN,NaN,NaN,NaN,NaN,CC BY-SA,NaN,NaN,NaN,...,NaN,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA,CC BY-NC-SA
clinical_notes,"On January 22, 2020, a 65-year-old man with a ...","On January 22, 2020, a 65-year-old man with a ...","On January 22, 2020, a 65-year-old man with a ...","On January 22, 2020, a 65-year-old man with a ...",diffuse infiltrates in the bilateral lower lungs,progressive diffuse interstitial opacities and...,Severe ARDS. Person is intubated with an OG in...,Case 2: chest x-ray obtained on Jan 6 (2A). Th...,Case 2: chest x-ray obtained on Jan 6 (2A). Th...,SARS in a 74-year-old man who developed sympto...,...,"posterior bilateral interstitial engagement, a...","Fever, cough and shortness of breath on arriva...","Fever, dry cough and dyspnea for few days. Mu...",Moderate amount of mid zone airspace opacifica...,just stepped down from HDU. New oxygen require...,"ITU admission, Endotracheal tube, nasogastric ...",Lines and tubes suitably sited. Minor regress...,increasing oxygen requirements. Extubated. Po...,Extubated since the prior radiograph. Partial...,Remarkable improvement in appearances since th...
other_notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Credit to Michele Pietragalla1, Letizia Vannuc...","Case courtesy of Dr Subhan Iqbal , Radiopaedia...","Case courtesy of Dr Şaban Tiryaki, Radiopaedia...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...","Case courtesy of Dr Ian Bickle, Radiopaedia.or..."
Unnamed: 28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Modelo bivaraible

In [3]:
df=pd.read_csv("metadata.csv")
df

,patientid,offset,sex,age,finding,survival,intubated,intubation_present,went_icu,in_icu,...,date,location,folder,filename,doi,url,license,clinical_notes,other_notes,Unnamed: 28
0,2,0.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 22, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-a-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
1,2,3.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 25, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-b-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
2,2,5.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 27, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-c-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
3,2,6.0,M,65.0,COVID-19,Y,NaN,NaN,NaN,NaN,...,"January 28, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-d-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN,NaN
4,4,0.0,F,52.0,COVID-19,NaN,NaN,NaN,NaN,NaN,...,"January 25, 2020","Changhua Christian Hospital, Changhua City, Ta...",images,nejmc2001573_f1a.jpeg,10.1056/NEJMc2001573,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,diffuse infiltrates in the bilateral lower lungs,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,205,11.0,M,55.0,COVID-19,Y,NaN,Y,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,"ITU admission, Endotracheal tube, nasogastric ...","Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
368,205,13.0,M,55.0,COVID-19,Y,NaN,Y,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,Lines and tubes suitably sited. Minor regress...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
369,205,20.0,M,55.0,COVID-19,Y,NaN,Y,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,increasing oxygen requirements. Extubated. Po...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
370,205,24.0,M,55.0,COVID-19,Y,NaN,N,Y,Y,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,Extubated since the prior radiograph. Partial...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN
371,205,28.0,M,55.0,COVID-19,Y,NaN,N,Y,N,...,NaN,"North Derbyshire, UK",images,covid-19-pneumonia-progression-and-regression-...,NaN,https://radiopaedia.org/cases/covid-19-pneumon...,CC BY-NC-SA,Remarkable improvement in appearances since th...,"Case courtesy of Dr Ian Bickle, Radiopaedia.or...",NaN

In [8]:
catb_transformer = ColumnTransformer(
    [('onehot',OneHotEncoder(categories=['No Finding','Disease'],handle_unknown='ignore',sparse_output=False), ["finding"])],
    remainder='passthrough',
    verbose_feature_names_out=False).set_output(transform="pandas")
df=catb_transformer.fit_transform(df)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).